function out = visitIrNodeAnalogFunction(thisVisitor, afNode, indentLevel)
    out = true;
    outStr = sprintf('AnalogFunction: %s, inList: %s, outList: %s',...
                                                afNode.getName(),...
                                cell2str_vapp(afNode.getInputList()),...
                                 cell2str_vapp(afNode.getOutputList()));
    thisVisitor.printIndent(outStr, indentLevel);
end