function out = visitIrNodeOperation(thisVisitor, opNode, indentLevel)
    out = true;
    outStr= sprintf('Operation: %s, ddtTopNode: %d, onDdtPath = %d',...
                                                 opNode.getOpType(),...
                                                 opNode.isDdtTopNode(),...
                                                 opNode.isOnDdtPath());
    thisVisitor.printIndent(outStr, indentLevel);
end
