function out = visitIrNodePotentialFlow(thisVisitor, pfNode, indentLevel)
    out = true;
    pfObj = pfNode.getPfObj;

    outStr = sprintf(['PotentialFlow: %s, pfObj: %s, inverse: %d, ',...
                      'probe: %d, contrib: %d'],...
                                                pfObj.getLabel(),...
                                                class(pfObj),...
                                                pfNode.isInverse(),...
                                                pfObj.isProbe(),...
                                                pfObj.isContrib());
    thisVisitor.printIndent(outStr, indentLevel);
end