function setRhsVecs(thisVisitor, digger)
    thisVisitor.rhsVarVec  = [thisVisitor.ifElseVarVec, ...
                                                    digger.getVarVec()];
    thisVisitor.rhsPfVec   = [thisVisitor.ifElsePfVec, ...
                                                    digger.getPfVec()];
    thisVisitor.rhsParmVec = [thisVisitor.ifElseParmVec, ...
                                                digger.getParmVec()];
end